## YAML Template.
message: This is a message defined in the configuration 
messageRepetitions: 10


# Database settings.
database:
    # the name of the JDBC driver, mysql in our case
    driverClass: com.mysql.jdbc.Driver
    # the username
    user: root
    # the password
    password: welcome
    # the JDBC URL; the database is called DWGettingStarted
    url: jdbc:mysql://localhost:3306/localoffer
